- name: Install apt-repo dependencies
  apt:
      name: "{{ packages }}"
      state: present
  vars:
      packages:
          - gnupg2
          - dirmngr
          - software-properties-common

- name: Install ppa:certbot
  apt_repository:
      repo: ppa:certbot/certbot
      state: present

- name: Update apt cache
  apt:
      update_cache: yes

- name: Install certbot for nginx
  apt:
      name: "{{ certbot }}"
      state: present
  vars:
      certbot:
          - certbot
          - python3-certbot-dns-cloudflare

- name: Remove old aria-ng nginx configuration file
  file:
      path: /etc/nginx/conf.d/{{ domain}}.conf
      state: absent

- name: Install CloudFlare credential
  template:
      src: cloudflare.ini.j2
      dest: /root/.cloudflare.ini
      owner: root
      group: root
      mode: '0400'

- name: Generate Let's Encrypt certificate
  command: certbot certonly --dns-cloudflare --dns-cloudflare-credentials /root/.cloudflare.ini --rsa-key-size 4096 --agree-tos --email {{ email }} -d {{ domain }} 

- name: Remove CloudFlare credential
  file:
      path: /root/.cloudflare.ini
      state: absent

- name: Install new nginx configuration file
  template:
      src: aria-ng.letsencrypt.conf.j2
      dest: /etc/nginx/conf.d/{{ domain }}.conf
      owner: www-data
      group: www-data
      mode: '0444'

- name: Install nginx secure cipher configuration
  template:
      src: ssl-options.conf.j2
      dest: /etc/nginx/ssl-options.conf
      owner: www-data
      group: www-data
      mode: '0444'

- name: Create dhparam.pem
  command: openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 4096

- name: Reload nginx
  systemd:
      name: nginx
      state: reloaded
